import VCF400Kit

enum L10n {
    static let mainSubtitle = "ようこそ Vintage Computer Festival 2024 へ"
    static let mainGuidance = "メニュー番号を入力して ENTER を押すか、項目をタップしてください。"
    static let groupStart = "はじめに"
    static let groupExhibit = "展示タスク"
    static let groupOffice = "オフィスタスク"
    static let groupSystem = "システムタスク"
    static let groupAdmin = "管理"
    static let groupEntertainment = "エンターテインメント"
    static let learnNavigation = "AS/400 ナビゲーションを学ぶ"
    static let history = "IBM ミッドレンジの歴史"
    static let aboutSystem = "このシステムについて"
    static let aboutGertie = "Gertie the System/34 について"
    static let nominate = "展示をアワードに推薦"
    static let signGuestbook = "展示のゲストブックに署名"
    static let readGuestbook = "ゲストブックのコメントを読む"
    static let officeVision = "OfficeVision/400 を起動"
    static let calendar = "カレンダーを起動"
    static let clock = "時計を起動"
    static let signOffSystem = "システムからサインオフ"
    static let adminMenu = "管理メニューを起動"
    static let snake = "Snake をプレイ"
    static let yahtzee = "Yahtzee をプレイ"
    static let pacman = "PacMan をプレイ"
    static let optionPrompt = "番号を入力して ENTER"
    static let signonDisclosure = "別のユーザープロファイルでサインオン (キオスク展示 / MM2024 共用端末)"
    static let profilePlaceholder = "ユーザープロファイル"
    static let signOn = "サインオン"
    static let kiosk = "キオスク:"
    static let navigationSubtitle = "開始する前に、操作方法をご案内します。"
    static let navigation1 = "1. 矢印キーまたは TAB キーで入力欄を移動します。"
    static let navigation2 = "2. F5 または ENTER で操作を実行します。"
    static let navigation3 = "3. F12 でいつでも終了できます。"
    static let navigation4 = "4. キーボードが反応しない場合、左隅に X II が表示されていれば RIGHT CTRL を押して続行します。"
    static let navigationFootnote = "この iPad UI では、各操作ボタンにも対応するファンクションキーを表示しています。"
    static let navigationReady = "準備はできましたか？"
    static let signedOff = "サインオフしました"
    static let sessionEnded = "セッションを終了しました。VCF/400 にお越しいただきありがとうございました。"
    static let signOnAgain = "再サインオン"
    static let signedOnAs = "サインオン:"
    static let sharedTerminal = " (共用端末)"
    static let voteSubtitle = "ヴィンテージ・コンピュータ・フェスティバル 2024"
    static let badgeLabel = "最初に SFGE バッジ番号を入力"
    static let exhibitLabel = "次に推薦する展示 ID を入力"
    static let awardLabel = "最後に選択するアワード ID を入力"
    static let digits4 = "4 桁"
    static let digits3 = "3 桁 (下記のアワード一覧を参照)"
    static let fixedExhibit = "この展示に固定されています (サインオンしたプロファイル)。MM2024 でサインオンすると任意の展示を入力できます。"
    static let sharedExhibit = "共用端末 (MM2024): 展示のユーザープロファイルを入力 (例: ASHIBATA)"
    static let availableAwards = "今年のアワード一覧:"
    static let oneAward = "投票できるアワードは 1 つだけです。慎重に推薦先を選んでください！"
    static let tabSubmit = "TAB = 入力欄切替 · ENTER = 送信"
    static let recorded = "投票を記録しました！"
    static let voteThanks = "ヴィンテージ・コンピュータ・フェスティバル・サウスイースト 2024 のアワードにご参加いただきありがとうございます。残りの展示とサザン・フライド・ゲーミング・エキスポをお楽しみください！"
    static let voteEndJa = "投票ありがとうございました！"
    static let endOfConJa = "申し訳ありません。"
    static let badge = "バッジ"
    static let exhibit = "展示"
    static let award = "アワード"
    static let voteEndFootnote = "ENTER を押してメインメニューに戻ります。"
    static let votingEnded = "投票期間が終了したため、投票できません。"
    static let guestbookInstead = "よろしければ、この展示のゲストブックに署名できます。"
    static let name = "お名前"
    static let upTo16 = "16 文字まで"
    static let exhibitID = "展示 ID"
    static let fixedToExhibit = "この展示に固定されています (サインオンしたプロファイル)。"
    static let sharedTypeExhibit = "共用端末 (MM2024): 展示のユーザープロファイルを入力"
    static let comment = "コメント"
    static let upTo200 = "200 文字まで"
    static let commentThanks = "この展示にコメントをお寄せいただきありがとうございます。コメント ID:"
    static let commentEndJa = "コメントをお寄せいただきありがとうございました！"
    static let enterCommentID = "コメント ID を入力:"
    static let currentComments = "現在のコメント総数: "
    static let saysTo = "→ 宛先:"
    static let commentID = "コメント ID"
    static let reportComment = "このコメントに問題がありますか？コメント ID を Midrange Madness テーブルのスタッフにお知らせください。対応します。"
    static let learnPage = "ページ"
    static let learnLegend = "Cmd3/F3 = 終了 · Cmd5/F5 = 次へ · Cmd8/F8 = 前へ"
    static let kioskSubtitle = "展示キオスク"
    static let hostedBy = "出展者: "
    static let notFound = "展示"
    static let kioskMenu1 = "この展示をアワードに推薦"
    static let kioskMenu2 = "この展示について詳しく学ぶ"
    static let kioskMenu3 = "展示のゲストブックに署名"
    static let kioskMenu4 = "展示のゲストブックを読む"
    static let kioskOption = "メニューオプションを選択して ENTER:"
    static let adminTitle = "キオスクを終了しますか？"
    static let adminOriginal = "Are you sure you want to exit the kiosk?"
    static let adminSubtitle = "管理者パスワードを入力して ENTER を押し、サインオフします"
    static let adminPassword = "管理者パスワード"
    static let pwLocked = "パスワードの入力に連続で失敗したため、30 秒間入力を停止しています。"
    static let dbOpenFailed = "データベースを開けませんでした (%@)。一時的なメモリ上のデータで起動しています。"
    static let menuOptionMissing = "メニュー番号 %@ は VCF/400 ライブラリに含まれていません。"
    static let invalidOption = "無効なオプションです。メニュー番号を入力して ENTER を押してください。"
    static let exhibitMissing = "展示 %@ が見つかりません。"
    static let selectOption = "メニューオプションを選択して ENTER を押してください。"
    static let kioskEnded = "キオスク %@ を終了しました。"

    static let messageJa: [String: String] = [
        Messages.errblkbg: "バッジ番号を入力してください",
        Messages.errblkex: "展示 ID を入力してください",
        Messages.errblkaw: "アワード ID を入力してください",
        Messages.errexist: "すでに投票済みです。",
        Messages.errprohb: "この展示はアワード対象外です",
        Messages.errnoexb: "展示が存在しません",
        Messages.errnoawd: "アワードが存在しません。",
        Messages.errnoname: "お名前を入力してください",
        Messages.errnocmt: "コメントを入力してください",
        Messages.errcmtid: "コメント ID を入力してください"
    ]

    static func ja(_ english: String) -> String {
        messageJa[english] ?? english
    }
}
