-- DB2 for i 相当スキーマ (元 DDS: QDDSSRC/*.pf). B型 -> SMALLINT/INTEGER, A型 -> CHAR(n), UNIQUE キー -> PRIMARY KEY
-- D-01 EXHBDB (展示)
CREATE TABLE IF NOT EXISTS EXHBDB (
  EXHBDBID   SMALLINT      NOT NULL,          -- 3B 0
  EXHUSRPRF  CHAR(9)       NOT NULL,          -- 9A  KEY (展示 ID = ユーザープロファイル)
  EXHBITOR   CHAR(20)      NOT NULL DEFAULT '',
  EXHBCITY   CHAR(20)      NOT NULL DEFAULT '',
  EXHBSTATE  CHAR(2)       NOT NULL DEFAULT '',
  EXHBTITLE  CHAR(50)      NOT NULL DEFAULT '',
  EXHBDESC   CHAR(1000)    NOT NULL DEFAULT '',
  ELIGIBLE   SMALLINT      NOT NULL DEFAULT 0, -- 1B 0
  ENLRN400   SMALLINT      NOT NULL DEFAULT 0, -- 1B 0
  PRIMARY KEY (EXHUSRPRF)
);

-- D-02 VOTINGDB (投票) : 1 バッジ 1 票
CREATE TABLE IF NOT EXISTS VOTINGDB (
  BADGENBR   INTEGER       NOT NULL,          -- 4B 0 KEY
  AWARDNBR   SMALLINT      NOT NULL,          -- 3B 0
  EXHBNBR    CHAR(9)       NOT NULL,          -- 9A
  PRIMARY KEY (BADGENBR)
);

-- D-03 GUESTBKDB (ゲストブック)
CREATE TABLE IF NOT EXISTS GUESTBKDB (
  CMTID      INTEGER       NOT NULL,          -- 4B 0 KEY
  VISIBLE    CHAR(1)       NOT NULL DEFAULT 'Y',
  EXHBID     CHAR(9)       NOT NULL,
  GUESTNAME  CHAR(20)      NOT NULL DEFAULT '',
  GUESTCMT   CHAR(200)     NOT NULL DEFAULT '',
  PRIMARY KEY (CMTID)
);

-- D-04 AWARDDB (アワード)
CREATE TABLE IF NOT EXISTS AWARDDB (
  AWARDID    SMALLINT      NOT NULL,          -- 3B 0 KEY
  AWARDTITLE CHAR(100)     NOT NULL DEFAULT '',
  AWARDDESC  CHAR(1000)    NOT NULL DEFAULT '',
  PRIMARY KEY (AWARDID)
);

-- D-05 SETTINGS (設定) : ADMPSWRD / ALWVOTE
CREATE TABLE IF NOT EXISTS SETTINGS (
  SETTING    CHAR(9)       NOT NULL,          -- 9A KEY
  VALUE      CHAR(9)       NOT NULL DEFAULT '',
  PRIMARY KEY (SETTING)
);

-- D-06 SECOFRS (管理者)
CREATE TABLE IF NOT EXISTS SECOFRS (
  USERPROF   CHAR(9)       NOT NULL,
  PRIMARY KEY (USERPROF)
);

-- D-07 LRN400STR (LEARN/400 ページ)
CREATE TABLE IF NOT EXISTS LRN400STR (
  PAGENBR    INTEGER       NOT NULL,          -- 4B 0 KEY
  CONTENT    CHAR(1500)    NOT NULL DEFAULT '',
  EXTRA      CHAR(9)       NOT NULL DEFAULT '',
  PRIMARY KEY (PAGENBR)
);
