CREATE TABLE VOTINGDB (BADGENBR INTEGER PRIMARY KEY, AWARDNBR INTEGER NOT NULL, EXHBNBR VARCHAR(9) NOT NULL);
CREATE TABLE AWARDDB (AWARDID INTEGER PRIMARY KEY, AWARDTITLE VARCHAR(100) NOT NULL, AWARDDESC VARCHAR(1000));
CREATE TABLE EXHBDB (EXHBDBID INTEGER NOT NULL, EXHUSRPRF VARCHAR(9) PRIMARY KEY, EXHBITOR VARCHAR(20), EXHBCITY VARCHAR(20), EXHBSTATE VARCHAR(2), EXHBTITLE VARCHAR(50), EXHBDESC VARCHAR(1000), ELIGIBLE INTEGER NOT NULL, ENLRN400 INTEGER NOT NULL);
CREATE TABLE GUESTBKDB (CMTID INTEGER PRIMARY KEY, VISIBLE VARCHAR(1) NOT NULL, EXHBID VARCHAR(9) NOT NULL, GUESTNAME VARCHAR(20), GUESTCMT VARCHAR(200));
CREATE TABLE LRN400STR (OWNER VARCHAR(9) DEFAULT 'LRN400STR' NOT NULL, PAGENBR INTEGER NOT NULL, CONTENT VARCHAR(1500), EXTRA VARCHAR(9), PRIMARY KEY (OWNER, PAGENBR));
CREATE TABLE SECOFRS (USERPROF VARCHAR(9) PRIMARY KEY);
CREATE TABLE SETTINGS (SETTING VARCHAR(9) PRIMARY KEY, VALUE VARCHAR(9));
CREATE TABLE BMOVDB (SPEAKER VARCHAR(9), LINE VARCHAR(50) PRIMARY KEY);
